[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gestion_de_eventos = "9hTWVDR6UAWR14cD8AWtfozaFH6Qc7bZZuWKvA2zHkZt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ariel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
